import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const logStep = (step: string, details?: any) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[CREATE-INVOICE] ${step}${detailsStr}`);
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

  try {
    logStep("Function started");

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header provided");

    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userError } = await supabaseClient.auth.getUser(token);
    if (userError) throw new Error(`Authentication error: ${userError.message}`);
    const user = userData.user;
    if (!user) throw new Error("User not authenticated");
    logStep("User authenticated", { userId: user.id });

    const { 
      payment_type, 
      payment_id, 
      user_id, 
      amount_usd, 
      credits, 
      description,
      customer_name,
      customer_email,
      customer_address,
      notes,
      status = 'paid'
    } = await req.json();

    // Validate required fields
    if (!user_id || !amount_usd || !credits || !payment_type) {
      throw new Error("Missing required fields: user_id, amount_usd, credits, payment_type");
    }

    logStep("Creating invoice", { payment_type, amount_usd, credits });

    // Check if invoice already exists for this payment
    if (payment_id) {
      const { data: existingInvoice } = await supabaseClient
        .from('invoices')
        .select('id, invoice_number')
        .eq('payment_id', payment_id)
        .eq('payment_type', payment_type)
        .single();

      if (existingInvoice) {
        logStep("Invoice already exists", { invoiceId: existingInvoice.id });
        return new Response(JSON.stringify({ 
          success: true, 
          invoice: existingInvoice,
          message: "Invoice already exists"
        }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 200,
        });
      }
    }

    // Get customer details if not provided
    let finalCustomerName = customer_name;
    let finalCustomerEmail = customer_email;
    
    if (!finalCustomerName || !finalCustomerEmail) {
      const { data: profile } = await supabaseClient
        .from('profiles')
        .select('full_name, email')
        .eq('id', user_id)
        .single();
      
      if (profile) {
        finalCustomerName = finalCustomerName || profile.full_name || 'Customer';
        finalCustomerEmail = finalCustomerEmail || profile.email;
      }
    }

    // Create the invoice
    const { data: invoice, error: insertError } = await supabaseClient
      .from('invoices')
      .insert({
        user_id,
        amount_usd,
        credits,
        payment_type,
        payment_id: payment_id || null,
        description: description || `${credits} Document Check Credits`,
        customer_name: finalCustomerName,
        customer_email: finalCustomerEmail,
        customer_address: customer_address || null,
        notes: notes || null,
        status,
        paid_at: status === 'paid' ? new Date().toISOString() : null,
        created_by: user.id,
        invoice_number: '' // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (insertError) throw new Error(`Failed to create invoice: ${insertError.message}`);
    
    logStep("Invoice created successfully", { invoiceId: invoice.id, invoiceNumber: invoice.invoice_number });

    return new Response(JSON.stringify({ 
      success: true, 
      invoice 
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logStep("ERROR", { message: errorMessage });
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
