import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { FileCheck, Shield, Zap, Globe, Mail, ArrowLeft } from 'lucide-react';
import Footer from '@/components/Footer';

export default function AboutUs() {
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container-width flex h-16 items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-lg gradient-primary flex items-center justify-center">
              <FileCheck className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="font-display font-bold text-lg">PlagaiScans</span>
          </Link>
          <Link to="/">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>
      </nav>

      {/* Main Content */}
      <main className="container-width px-4 py-16">
        <div className="max-w-4xl mx-auto">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-display font-bold mb-6">
              About <span className="text-primary">PlagaiScans</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Professional document similarity and AI content detection services for academic integrity and content verification.
            </p>
          </div>

          {/* Company Info */}
          <Card className="mb-12">
            <CardContent className="p-8">
              <h2 className="text-2xl font-bold mb-4">Who We Are</h2>
              <p className="text-muted-foreground mb-4">
                PlagaiScans is a professional document analysis service operated by <strong>Goldfeather Prem Ltd</strong>, 
                a company registered in the <strong>United Kingdom</strong>. We provide advanced similarity detection 
                and AI content analysis to help individuals and organizations maintain academic and content integrity.
              </p>
              <p className="text-muted-foreground mb-4">
                Our platform utilizes sophisticated algorithms and comprehensive databases to analyze documents 
                for similarity against billions of academic papers, websites, and publications. Additionally, 
                our AI detection technology identifies content generated by artificial intelligence tools.
              </p>
              <p className="text-muted-foreground">
                We are committed to providing accurate, reliable, and confidential document analysis services 
                while maintaining the highest standards of data security and privacy.
              </p>
            </CardContent>
          </Card>

          {/* Features Grid */}
          <div className="grid md:grid-cols-2 gap-6 mb-12">
            <Card>
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <FileCheck className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-xl font-bold mb-2">Similarity Detection</h3>
                <p className="text-muted-foreground">
                  Advanced plagiarism detection comparing documents against billions of academic sources, 
                  websites, and publications worldwide.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-lg bg-secondary/10 flex items-center justify-center mb-4">
                  <Shield className="h-6 w-6 text-secondary" />
                </div>
                <h3 className="text-xl font-bold mb-2">AI Content Detection</h3>
                <p className="text-muted-foreground">
                  State-of-the-art detection of AI-generated content from various sources including 
                  ChatGPT, Claude, and other AI writing tools.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <Zap className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-xl font-bold mb-2">Fast Processing</h3>
                <p className="text-muted-foreground">
                  Get detailed analysis reports in minutes, not hours. Our efficient system ensures 
                  quick turnaround times for all submissions.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-lg bg-secondary/10 flex items-center justify-center mb-4">
                  <Globe className="h-6 w-6 text-secondary" />
                </div>
                <h3 className="text-xl font-bold mb-2">Global Coverage</h3>
                <p className="text-muted-foreground">
                  Our comprehensive database includes sources from around the world, ensuring 
                  thorough analysis across languages and regions.
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Contact Section */}
          <Card className="bg-primary/5 border-primary/20">
            <CardContent className="p-8 text-center">
              <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
              <p className="text-muted-foreground mb-6">
                Have questions about our services? We're here to help.
              </p>
              <div className="flex items-center justify-center gap-2 text-lg">
                <Mail className="h-5 w-5 text-primary" />
                <a href="mailto:support@plagaiscans.com" className="text-primary hover:underline font-medium">
                  support@plagaiscans.com
                </a>
              </div>
              <p className="text-sm text-muted-foreground mt-6">
                Goldfeather Prem Ltd • United Kingdom
              </p>
            </CardContent>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
}
